language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
notifications:
  irc: "irc.freenode.org#nens"
  email: false
before_install:
  - sudo apt-get build-dep python-psycopg2
install:
  - pip install pep8 --use-mirrors
  - pip install psycopg2
  - python bootstrap.py 
script:
  - bin/buildout 
  - pep8 --exclude=migrations --ignore=E501,E225 lizard_blockbox
