language: python
python:
  - 2.6
  - 2.7
notifications:
  irc: "irc.freenode.org#nens"
  email: false
before_install:
  - sudo apt-get install python-psycopg2
install:
  - deactivate
  - python bootstrap.py
script:
  - bin/buildout
  - bin/pep8 --exclude=migrations --ignore=E123,E126,E225,E501 lizard_blockbox
