# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 13:41
from __future__ import unicode_literals
from django.core import serializers
from django.db import migrations

import os


fixture_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../fixtures"))


def load_map_fixtures(apps, schema_editor):
    filename = os.path.join(fixture_path, "lizard_map.json")

    with open(filename, "rb") as fixture:
        for obj in serializers.deserialize("json", fixture):
            obj.save()


def remove_maps(apps, schema_editor):
    backgroundmap = apps.get_model("lizard_map", "backgroundmap")
    backgroundmap.objects.all().delete()

    setting = apps.get_model("lizard_map", "setting")
    setting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lizard_blockbox", "0001_initial"),
        ("lizard_map", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_map_fixtures, remove_maps),
    ]
